# Generated by Django 3.2.2 on 2021-06-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_assignment_details_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment_details',
            name='upload_answer',
            field=models.FileField(default='no file', upload_to='files/'),
        ),
    ]
