# Generated by Django 3.2.2 on 2021-06-10 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_assignment_details_upload_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment_details',
            name='upload_answer',
        ),
    ]
