# Generated by Django 3.2.2 on 2021-06-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_remove_assignment_details_upload_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment_details',
            name='upload',
            field=models.FileField(default='no file', upload_to='files'),
        ),
    ]
