# Generated by Django 3.2.2 on 2021-06-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0006_assignment_details_upload_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='assignment_answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_registration', models.CharField(max_length=100)),
                ('upload_answer', models.FileField(default='no file', upload_to='files/')),
            ],
        ),
        migrations.RemoveField(
            model_name='assignment_details',
            name='upload_answer',
        ),
    ]
