# Generated by Django 3.2.2 on 2021-06-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0007_auto_20210610_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment_answer',
            name='class_code',
            field=models.CharField(default=1001, max_length=100),
            preserve_default=False,
        ),
    ]
