# Generated by Django 3.2.3 on 2021-06-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0008_assignment_answer_class_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment_details',
            name='registration',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
