# Generated by Django 3.2.3 on 2021-06-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notes_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursecode', models.CharField(max_length=100)),
                ('coursename', models.CharField(max_length=100)),
                ('topicname', models.CharField(default=123, max_length=100)),
                ('notesfile', models.FileField(upload_to='images')),
            ],
        ),
    ]
