# Generated by Django 3.2.3 on 2021-06-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes_table',
            name='topicname',
            field=models.CharField(max_length=100),
        ),
    ]
