# Generated by Django 3.2.3 on 2021-06-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesd', '0002_alter_notes_table_topicname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes_table',
            name='notesfile',
            field=models.FileField(upload_to='files'),
        ),
    ]
