# Generated by Django 3.2.3 on 2021-06-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0009_auto_20210520_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='asg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultyname', models.CharField(default='aaaaaa', max_length=100)),
                ('coursecode', models.CharField(default='00000', max_length=100)),
                ('coursename', models.CharField(default='00000', max_length=100)),
                ('topicname', models.CharField(default='aaaaaa', max_length=100)),
                ('pdf', models.FileField(upload_to='notes/pdf/')),
            ],
        ),
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultyname', models.CharField(default='aaaaaa', max_length=100)),
                ('coursecode', models.CharField(default='00000', max_length=100)),
                ('coursename', models.CharField(default='00000', max_length=100)),
                ('topicname', models.CharField(default='aaaaaa', max_length=100)),
                ('pdf', models.FileField(upload_to='notes/pdf/')),
            ],
        ),
    ]
