# Generated by Django 3.2.3 on 2021-06-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0010_asg_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='registration',
            field=models.CharField(default='123', max_length=100),
        ),
    ]
